import { Routes } from '@angular/router';
import { Docs } from './docs/docs';

export const routes: Routes = [
  { path: '', redirectTo: 'docs/introduction', pathMatch: 'full' },
  {
    path: 'docs',
    component: Docs,
    children: [
      { path: 'introduction', loadComponent: () => import('./pages/introduction/introduction').then(m => m.IntroductionPage) },
      { path: 'installation', loadComponent: () => import('./pages/installation/installation').then(m => m.InstallationPage) },
      { path: 'components-json', loadComponent: () => import('./pages/components-json/components-json').then(m => m.ComponentsJsonPage) },
      { path: 'theming', loadComponent: () => import('./pages/theming/theming').then(m => m.ThemingPage) },
      { path: 'dark-mode', loadComponent: () => import('./pages/dark-mode/dark-mode').then(m => m.DarkModePage) },
      { path: 'health-checks', loadComponent: () => import('./pages/health-checks/health-checks').then(m => m.HealthChecksPage) },
      { path: 'typography', loadComponent: () => import('./pages/typography/typography').then(m => m.TypographyPage) },
      { path: 'accordion', loadComponent: () => import('./pages/accordion/accordion.page').then(m => m.AccordionPage) },
      { path: 'alert', loadComponent: () => import('./pages/alert/alert.page').then(m => m.AlertPage) },
      { path: 'alert-dialog', loadComponent: () => import('./pages/alert-dialog/alert-dialog.page').then(m => m.AlertDialogPage) },
      { path: 'aspect-ratio', loadComponent: () => import('./pages/aspect-ratio/aspect-ratio.page').then(m => m.AspectRatioPage) },
      { path: 'autocomplete', loadComponent: () => import('./pages/autocomplete/autocomplete.page').then(m => m.AutocompletePage) },
      { path: 'avatar', loadComponent: () => import('./pages/avatar/avatar.page').then(m => m.AvatarPage) },
      { path: 'badge', loadComponent: () => import('./pages/badge/badge.page').then(m => m.BadgePage) },
      { path: 'breadcrumb', loadComponent: () => import('./pages/breadcrumb/breadcrumb.page').then(m => m.BreadcrumbPage) },
      { path: 'button', loadComponent: () => import('./pages/button/button.page').then(m => m.ButtonPage) },
      { path: 'button-group', loadComponent: () => import('./pages/button-group/button-group.page').then(m => m.ButtonGroupPage) },
      { path: 'calendar', loadComponent: () => import('./pages/calendar/calendar.page').then(m => m.CalendarPage) },
      { path: 'card', loadComponent: () => import('./pages/card/card.page').then(m => m.CardPage) },
      { path: 'carousel', loadComponent: () => import('./pages/carousel/carousel.page').then(m => m.CarouselPage) },
      { path: 'chart', loadComponent: () => import('./pages/chart/chart').then(m => m.ChartPage) },
      { path: 'checkbox', loadComponent: () => import('./pages/checkbox/checkbox.page').then(m => m.CheckboxPage) },
      { path: 'collapsible', loadComponent: () => import('./pages/collapsible/collapsible.page').then(m => m.CollapsiblePage) },
      { path: 'combobox', loadComponent: () => import('./pages/combobox/combobox.page').then(m => m.ComboboxPage) },
      { path: 'command', loadComponent: () => import('./pages/command/command.page').then(m => m.CommandPage) },
      { path: 'context-menu', loadComponent: () => import('./pages/context-menu/context-menu.page').then(m => m.ContextMenuPage) },
      { path: 'data-table', loadComponent: () => import('./pages/data-table/data-table.page').then(m => m.DataTablePage) },
      { path: 'date-picker', loadComponent: () => import('./pages/date-picker/date-picker.page').then(m => m.DatePickerPage) },
      { path: 'dialog', loadComponent: () => import('./pages/dialog/dialog.page').then(m => m.DialogPage) },
      { path: 'dropdown-menu', loadComponent: () => import('./pages/dropdown-menu/dropdown-menu.page').then(m => m.DropdownMenuPage) },
      { path: 'empty', loadComponent: () => import('./pages/empty/empty.page').then(m => m.EmptyPage) },
      { path: 'field', loadComponent: () => import('./pages/field/field.page').then(m => m.FieldPage) },
      { path: 'hover-card', loadComponent: () => import('./pages/hover-card/hover-card.page').then(m => m.HoverCardPage) },
      { path: 'icon', loadComponent: () => import('./pages/icon/icon.page').then(m => m.IconPage) },
      { path: 'input', loadComponent: () => import('./pages/input/input.page').then(m => m.InputPage) },
      { path: 'input-group', loadComponent: () => import('./pages/input-group/input-group.page').then(m => m.InputGroupPage) },
      { path: 'input-otp', loadComponent: () => import('./pages/input-otp/input-otp.page').then(m => m.InputOtpPage) },
      { path: 'item', loadComponent: () => import('./pages/item/item.page').then(m => m.ItemPage) },
      { path: 'kbd', loadComponent: () => import('./pages/kbd/kbd.page').then(m => m.KbdPage) },
      { path: 'label', loadComponent: () => import('./pages/label/label.page').then(m => m.LabelPage) },
      { path: 'menubar', loadComponent: () => import('./pages/menubar/menubar.page').then(m => m.MenubarPage) },
      { path: 'native-select', loadComponent: () => import('./pages/native-select/native-select.page').then(m => m.NativeSelectPage) },
      { path: 'navigation-menu', loadComponent: () => import('./pages/navigation-menu/navigation-menu.page').then(m => m.NavigationMenuPage) },
      { path: 'pagination', loadComponent: () => import('./pages/pagination/pagination.page').then(m => m.PaginationPage) },
      { path: 'popover', loadComponent: () => import('./pages/popover/popover.page').then(m => m.PopoverPage) },
      { path: 'progress', loadComponent: () => import('./pages/progress/progress.page').then(m => m.ProgressPage) },
      { path: 'radio-group', loadComponent: () => import('./pages/radio-group/radio-group.page').then(m => m.RadioGroupPage) },
      { path: 'resizable', loadComponent: () => import('./pages/resizable/resizable.page').then(m => m.ResizablePage) },
      { path: 'scroll-area', loadComponent: () => import('./pages/scroll-area/scroll-area.page').then(m => m.ScrollAreaPage) },
      { path: 'select', loadComponent: () => import('./pages/select/select.page').then(m => m.SelectPage) },
      { path: 'separator', loadComponent: () => import('./pages/separator/separator.page').then(m => m.SeparatorPage) },
      { path: 'sheet', loadComponent: () => import('./pages/sheet/sheet.page').then(m => m.SheetPage) },
      { path: 'sidebar', loadComponent: () => import('./pages/sidebar/sidebar.page').then(m => m.SidebarPage) },
      { path: 'skeleton', loadComponent: () => import('./pages/skeleton/skeleton.page').then(m => m.SkeletonPage) },
      { path: 'slider', loadComponent: () => import('./pages/slider/slider.page').then(m => m.SliderPage) },
      { path: 'sonner', loadComponent: () => import('./pages/sonner/sonner.page').then(m => m.SonnerPage) },
      { path: 'spinner', loadComponent: () => import('./pages/spinner/spinner.page').then(m => m.SpinnerPage) },
      { path: 'switch', loadComponent: () => import('./pages/switch/switch.page').then(m => m.SwitchPage) },
      { path: 'table', loadComponent: () => import('./pages/table/table.page').then(m => m.TablePage) },
      { path: 'tabs', loadComponent: () => import('./pages/tabs/tabs.page').then(m => m.TabsPage) },
      { path: 'textarea', loadComponent: () => import('./pages/textarea/textarea.page').then(m => m.TextareaPage) },
      { path: 'toggle', loadComponent: () => import('./pages/toggle/toggle.page').then(m => m.TogglePage) },
      { path: 'toggle-group', loadComponent: () => import('./pages/toggle-group/toggle-group.page').then(m => m.ToggleGroupPage) },
      { path: 'tooltip', loadComponent: () => import('./pages/tooltip/tooltip.page').then(m => m.TooltipPage) },
    ]
  },
  { path: '**', redirectTo: 'docs/introduction' }
];
